### ISSUE TITLE
Add support for recurring tasks

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks-provider#1]
The task provider needs support for recurring tasks. That is, the instances of a task with `RRULE` or `RDATE` values have to be expanded and stored in the instances table.

If a task has neither a `DTSTART` nor a `DUE` value no instances get expanded.

A second table should contain the completed and the upcoming incomplete instance of a series of tasks. This table doesn't exist yet and needs to be created.

There already is a library to evaluate any `RRULE` values: https://github.com/dmfs/lib-recur

**Comment by Lykos153** [comment]
Is there an ETA for this feature?

**Comment by dmfs** [comment]
Sorry, no ETA. We're working on that, but at present we're quite busy with paid work.
The goal is to finish it before the end of this year.

**Comment by languitar** [comment]
I'm also interested in this.

**Comment by jpthorn01** [comment]
Do you guys need help implementing this? This would be a great feature to add.

**Comment by dmfs** [comment]
Issue moved to [dmfs/opentasks #367](https://github.com/dmfs/opentasks/issues/367) via [**ZenHub**](https://www.zenhub.com/)
