### ISSUE TITLE
Give more information about affected task if validation fails

### ISSUE THREAD

**Issue by korelstar** [dmfs/opentasks-provider#8]
`TaskValidatorProcessor` throws an `IllegalArgumentException` if a task does not comply with all constraints. However, sometimes it is not possible to reproduce which task is affected. Therefore, it would be nice, if the exception's message would contain some information in order to identify the affected task, i.e., it's title.

Background and motivation: if there are tasks on a server with `DUE < START` (yes, that is not allowed but some server do not enforce this) and these tasks should be synchronized using e.g. DAVdroid with OpenTasks. Now, the user gets the error message `DUE must not be < DTSTART` but is not able to find out which tasks are affected, without complicated and time-consuming debugging. Extending the exception's message with the task title would be very helpful in order to quickly correct the wrong data on the server.

See also this discussion: https://forums.bitfire.at/topic/1178/more-details-on-error-due-must-not-be-dtstart

**Comment by dmfs** [comment]
Issue moved to [dmfs/opentasks #366](https://github.com/dmfs/opentasks/issues/366) via [**ZenHub**](https://www.zenhub.com/)
